remote_theme: "mmistakes/minimal-mistakes"
title: "Don Ma | Data/ML Profile"
description: "Personal blog documenting side projects, technical reading, and thoughts on data and ML/AI."
# Important: Set your timezone
timezone: "Asia/Hong_Kong"
